# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VendingMachine' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Quick'
  pod 'Nimble'
  # Pods for VendingMachine

  target 'VendingMachineTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
